# Site settings
title: Blog
email: ankusth@yahoo.com
#description: > # this means to ignore newlines until "baseurl:" -Core developer 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ankusth.github.io" # the base hostname & protocol for your site
#twitter_username: lomi525
github_username:  ankusth
twitter_username: ankusth
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Github
    link: https://github.com/ankusth
  option2:
    name: Twitter
    link: https://twitter.com/ankusth
  

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
